version: '3.0'
services: 
    myapp1-es-01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        ports: 
            - "9200:9200"
            - "9300:9300"
        environment: 
            - "discovery.type=single-node"
            - "node.name=myapp1-es-01"
            - "cluster.name=myapp1-es-7.8.0"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            memlock:
                soft: -1
                hard: -1

        networks: 
            - "myapp1"
        volumes: 
            - esdata01:/usr/share/elasticsearch/data
    myapp1-kibana-01:
        image: docker.elastic.co/kibana/kibana:7.8.0
        ports: 
            - "5601:5601"
        networks: 
            - "myapp1"
        links: 
            - "myapp1-es-01:elasticsearch"
        depends_on: 
            - "myapp1-es-01"

volumes: 
    esdata01:
        driver: local
networks:
    myapp1:
        driver: "bridge"